---
kind: pipeline
name: build & test
trigger:
  branch:
    - main
  event:
    - push
steps:
  - name: test
    image: node:18.12-alpine3.17
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_token
    commands:
      - apk add --no-cache libc6-compat
      - corepack enable && corepack prepare --activate
      - yarn install
      - yarn lint
      - yarn test
      - yarn coverage
  - name: release
    image: node:18.12-alpine3.17
    environment:
      NPM_TOKEN:
        from_secret: npm_publish_token
    commands:
      - apk add --no-cache libc6-compat
      - yarn release