version: 2.1

general:
  branches:
    only:
     - master
     - develop
     - /feature/.*/

references:
  defaults: &defaults
    working_directory: ~
    docker:
      - image: circleci/node:11.10.1-browsers
  update_npm: &update_npm
    run:
      name: "Update npm"
      command: 'sudo npm install -g npm@latest'
  install_node_modules: &install_node_modules
    run:
      name: "Install node modules"
      command: 'npm install'
  link_packages: &link_packages
    run:
      name: "Link all packages"
      command: "npm run link:all"
  build_packages: &build_packages
    run:
      name: "Build all packages"
      command: "npm run build:all"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *update_npm
      - *install_node_modules
      - *link_packages
      - *build_packages
  test:
    <<: *defaults
    steps:
      - checkout
      - *update_npm
      - *install_node_modules
      - *link_packages
      - *build_packages
      - run:
          name: "Run TSLinter on all packages"
          command: "npm run lint:all"
      - run:
          name: "Run Jest on all packages"
          command: "npm run test:all"
  deploy:
    <<: *defaults
    steps:
      - checkout
      - *update_npm
      - *install_node_modules
      - *link_packages
      - run: echo "Deploy to npm..."

workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
  deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^@smoovy\/.*/
      - test:
          requires:
            - build
      - approval:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - approval
            - build
            - test
