version: 2.1

general:
  branches:
    only:
     - master
     - develop
     - /feature/.*/

references:
  defaults: &defaults
    working_directory: ~
    docker:
      - image: circleci/node:11.10.1-browsers
  update_npm: &update_npm
    run:
      name: "Update npm"
      command: 'sudo npm install -g npm@latest'
  install_node_modules: &install_node_modules
    run:
      name: "Install node modules"
      command: 'npm install'
  link_packages: &link_packages
    run:
      name: "Link all packages"
      command: "npm run link:all"
  build_packages: &build_packages
    run:
      name: "Build all packages"
      command: "npm run build:all"
  lint_packages: &lint_packages
    run:
      name: "Run TSLinter on all packages"
      command: "npm run lint:all"
  test_packages: &test_packages
    run:
      name: "Run Jest on all packages"
      command: "npm run test:all"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *update_npm
      - *install_node_modules
      - *link_packages
      - *build_packages
  build_test:
    <<: *defaults
    steps:
      - checkout
      - *update_npm
      - *install_node_modules
      - *link_packages
      - *build_packages
      - *lint_packages
      - *test_packages
  build_deploy:
    <<: *defaults
    steps:
      - checkout
      - *update_npm
      - *install_node_modules
      - *link_packages
      - *build_packages
      - run:
          name: "Add npm token"
          command: "echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc"
      - run:
          name: "Publish from git tags"
          command: "npm run publish:tag $CIRCLE_TAG"

workflows:
  build_test:
    jobs:
      - build_test
  build_test_deploy:
    jobs:
      - build_test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^@smoovy\/.*/
      - build_deploy:
          requires:
            - build_test
          filters:
            tags:
              only: /^@smoovy\/.*/
            branches:
              ignore: /.*/
