version: 2.1
jobs:
  test:
    working_directory: ~
    docker:
      - image: circleci/node:11.10.1-browsers
    steps:
      - checkout
      - run:
          name: "Update npm"
          command: 'sudo npm install -g npm@latest'
      - run:
          name: "Install node modules"
          command: 'npm install'
      - run:
          name: "Link all packages"
          command: "npm run link:all"
      - run:
          name: "Run TSLinter on all packages"
          command: "npm run lint:all"
      - run:
          name: "Build all packages"
          command: "npm run build:all"
      - run:
          name: "Run Jest on all packages"
          command: "npm run test:all"
workflows:
  test:
    jobs:
      - test
