#!/usr/bin/env sh
PKG=$(pwd)/packages/$1
DEMO=$2

if [ -z "$2" ]
then
  echo "Using demo \"default\""
  DEMO="default"
fi

if [ -d "$PKG/demos" ];
then
  parcel --no-autoinstall $PKG/demos/$DEMO/index.html --out-dir $(pwd)/.dev --open
else
  echo "The package \"$1\" does not have any demos"
fi
