name: "Build and deploy"
on:
  push:
    tags:
      - "@smoovy/**"
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          PACKAGE=$(echo $GITHUB_REF | sed -r 's/refs\/tags\/@smoovy\/(.*)\@(.*)/\1/')
          echo "::set-env name=PACKAGE::${PACKAGE}"
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup node (v11.10.1)
        uses: actions/setup-node@v1
        with:
          node-version: '11.10.1'
      - name: Install node modules
        run: npm install
      - name: Bootstrap packages
        run: npm run bootstrap
      - name: Build package
        run: npm run build:package $PACKAGE
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/$PACKAGE && npm publish



