name: "[Deploy] Build and test"
on:
  push:
    branches:
      - master
      - feature/*
    tags:
      - '!refs/tags/*'
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          echo "::set-env name=CI::1"
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup node (v11.10.1)
        uses: actions/setup-node@v1
        with:
          node-version: '11.10.1'
      - name: Install node modules
        run: npm install
      - name: Bootstrap packages
        run: npm run bootstrap
      - name: Build packages
        run: npm run build:all
      - name: Lint packages
        run: npm run lint:all
      - name: Test packages
        run: npm run test:all
      - name: Report coverage
        if: github.ref == 'refs/heads/master'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npm run test:report



